# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b33b56f5e0957f815fd9e0431afb9aa855a4893e224b8a650aa28cbfc556bc42345186ae6c85efd9217ba0ed0e4218a14561103c378c88357989d76b2b33d0bc

test:
  secret_key_base: 4829a16ebb0399bfc2b1b82561504bee124449b4804a73e97ac498147656bacaae4c3e1ead1f611ecc0a7ab6f3e43696b9873b6fb6b1afc89a618881e1255906

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
